Add rational for using Meld
TellinaTool/tellina_user_experiment pull request #15
Opened 2020-12-15 18:58 UTC by Thomsch

This PR adds the rational of why Meld is used to show diffs rather than using the terminal directly.

2020-12-15 20:19 UTC, anhnamtran requested changes

2020-12-15 20:19 UTC, anhnamtran commented on experiment_design_doc.md
> +
Could you add a little caveat that this means that the participants will be required to have Mel's installed on whichever machine/platform they are on?

2020-12-15 23:47 UTC, Thomsch commented on experiment_design_doc.md
> +
Good idea!

2020-12-17 18:33 UTC, anhnamtran approved these changes
Ship It!

2020-12-17 20:10 UTC, merged